MySNS/MyApp/urls.py
from django.urls import path
from django.views.generic import RedirectView
from django.contrib.auth.views import LoginView, LogoutView

from .views import MyPageUpdateView, PostJsonView, UserPostListView, TalkView, PostView, MyPageView, PostDetailView, TalkDetailView, SignupView, PostCreateView, TalkCreateView, MyPageCreateView, MyPageJsonView
from .views import post_like, talk_like, login_signup

app_name = 'MyApp'

urlpatterns = [
    path('', RedirectView.as_view(url='index/', permanent=True)),

    path('index/', UserPostListView.as_view(), name="index"),

    path('talk/', TalkView.as_view(), name="talk"),
    path('talk/create', TalkCreateView.as_view(), name="talk_create"),
    path('talk/<int:pk>/', TalkDetailView.as_view(), name='talk_detail'),
    path('talk_like/', talk_like, name='talk_like'),

    path('post/', PostView.as_view(), name="post"),
    path('post/create', PostCreateView.as_view(), name="post_create"),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('post_like/', post_like, name='post_like'),
    path('post/json/', PostJsonView.as_view(), name='post_json'),
    
    path('myPage/create', MyPageCreateView.as_view(), name="myPage_create"),
    path('myPage/<int:pk>/update', MyPageUpdateView.as_view(), name="myPage_update"),
    path('myPage/<int:pk>', MyPageView.as_view(), name="myPage"),
    path('myPage/json/', MyPageJsonView.as_view(), name='post_json'),

    path('signup/', SignupView.as_view(), name='signup'),

    # path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('login/', login_signup, name='login'),
    path('logout/', LogoutView.as_view(next_page='MyApp:login'), name='logout'),

    path('login_signup/', login_signup, name='login_signup'),

    # path("detail/<int:pk>", detailfunc, name='detail'),
    # path("good/<int:pk>", goodfunc, name='good'),
    # path("read/<int:pk>", readfunc, name='read'),
    # path("create/", BoardCreate.as_view(), name='create'),
]

MySNS/MySNS/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MyApp.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MySNS/MyApp/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django.db import models

# class CustomUser(AbstractUser):
#     email = models.EmailField(blank=True, unique=True)
#     github_id = models.CharField(max_length=100, blank=True, null=True)

#---------------Post---------------------

class Post(models.Model):
    CATEGORY_CHOICES = (
        ('なし', 'なし'),
        ('AI', 'AI'),
        ('Python', 'Python'),
        ('java', 'java'),
    )

    title = models.CharField(max_length=50)
    content = models.TextField(max_length=1000)
    date_posted = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    image = models.ImageField(upload_to='post_images/', default="post_images/D.jpg")
    image2 = models.ImageField(upload_to='post_images/', null=True, blank=True)
    image3 = models.ImageField(upload_to='post_images/', null=True, blank=True)
    image4 = models.ImageField(upload_to='post_images/', null=True, blank=True)
    image5 = models.ImageField(upload_to='post_images/', null=True, blank=True)
    # image = models.ImageField(upload_to='post_images/', null=True, blank=True)

    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, default='なし')
    likes = models.ManyToManyField(User, related_name='post_likes', blank=True)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = "投稿"
        verbose_name_plural = "投稿一覧"


class PostLike(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('post', 'user')
        verbose_name = 'ポストいいね'
        verbose_name_plural = 'ポストいいね一覧'

class PostRead(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

#---------------Talk---------------------

class Talk(models.Model):
    content = models.TextField(max_length=500)
    date_posted = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name='talk_likes', blank=True)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.content
    
    class Meta:
        verbose_name = "トーク"
        verbose_name_plural = "トーク一覧"

class TalkLike(models.Model):
    talk = models.ForeignKey(Talk, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('talk', 'user')
        verbose_name = 'トークいいね'
        verbose_name_plural = 'トークいいね一覧'

class TalkRead(models.Model):
    talk = models.ForeignKey(Talk, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
 
#-----------mypage-----------------

class Profile(models.Model):

    GENDER_CHOICES = [
        ('男', '男'),
        ('女', '女'),
        ('その他', 'その他')
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=15, null=True, blank=True)
    posts = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='profile_posts', blank=True, null=True)
    icon = models.ImageField(null=True, blank=True, default="icons/default_icon.jpeg", upload_to='icons/')
    bio = models.TextField(max_length=200, null=True, blank=True)
    age = models.IntegerField(null=True, blank=True)
    gender = models.CharField(max_length=4, choices=GENDER_CHOICES, null=True, blank=True)
    university = models.CharField(max_length=50, null=True, blank=True)
    sns_account = models.CharField(max_length=50, null=True, blank=True)
    hobby = models.CharField(max_length=50, null=True, blank=True)
    language = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.user.username
    
    class Meta:
        verbose_name = "プロフィール"
        verbose_name_plural = "プロフィール一覧"

MySNS/MyApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Talk, Post

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=False, help_text='Required. Enter a valid email address.')
    github_id = forms.CharField(required=False, max_length=100)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'github_id')

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'image','image2', 'image3', 'image4', 'image5', 'category']


class TalkForm(forms.ModelForm):
    class Meta:
        model = Talk
        fields = ['content']

MySNS/MyApp/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy

from django.views.generic import ListView, CreateView, DetailView, UpdateView, TemplateView

from django.db.models import Count

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.http import JsonResponse

from django.views.decorators.http import require_POST

from .models import Post, PostLike, Talk, TalkLike, Profile

from .forms import CustomUserCreationForm, TalkForm, PostForm

class UserPostListView(ListView):
    model = Post
    template_name = 'index.html'
    context_object_name = 'posts'
    
    def get_queryset(self):
        author_id = self.kwargs.get('author_id')
        # return Post.objects.filter(author_id=author_id)
        return Post.objects.filter()

#------Post-----

class PostView(ListView):
    model = Post
    template_name = 'post.html'
    context_object_name = 'posts'
    
    def get_queryset(self):
        queryset = super().get_queryset()
        if 'popularity' in self.request.GET:
            queryset = queryset.annotate(num_likes=Count('postlike')).order_by('-num_likes')
        else:
            queryset = queryset.order_by('-date_posted')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        postlike_counts = []
        is_user_liked_for_posts = []
        for post in context['posts']:
            postlike_count = post.postlike_set.count()
            postlike_counts.append(postlike_count)
            
            if post.postlike_set.filter(user=self.request.user).exists():
                is_user_liked_for_post = True
            else:
                is_user_liked_for_post = False
            is_user_liked_for_posts.append(is_user_liked_for_post)

        context['postlike_count'] = postlike_counts
        context['is_user_liked_for_post'] = is_user_liked_for_posts

        return context
    
class PostDetailView(DetailView):
    model = Post
    template_name = 'postDetail.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        post = self.get_object()  # ポストを取得
        post.views += 1  # viewsを1増やす
        post.save()  # データベースに保存

        postlike_count = self.object.postlike_set.count()
        # ポストに対するイイね数
        context['postlike_count'] = postlike_count
        # ログイン中のユーザーがイイねしているかどうか
        if self.object.postlike_set.filter(user=self.request.user).exists():
            context['is_user_liked_for_post'] = True
        else:
            context['is_user_liked_for_post'] = False

        return context

# class PostCreateView(LoginRequiredMixin, CreateView):
#     model = Post
#     fields = ['title', 'content', 'image', 'category']
#     template_name = 'post_create.html'
#     success_url = reverse_lazy('MyApp:post')
    
#     def form_valid(self, form):
#         form.instance.author = self.request.user
#         return super().form_valid(form)

class PostCreateView(LoginRequiredMixin, TemplateView):
    template_name = 'post_create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.filter(author=self.request.user)
        context['form'] = PostForm()

        postlike_counts = []
        is_user_liked_for_posts = []
        for post in context['posts']:
            postlike_count = post.postlike_set.count()
            postlike_counts.append(postlike_count)
            
            if post.postlike_set.filter(user=self.request.user).exists():
                is_user_liked_for_post = True
            else:
                is_user_liked_for_post = False
            is_user_liked_for_posts.append(is_user_liked_for_post)

        context['postlike_count'] = postlike_counts
        context['is_user_liked_for_post'] = is_user_liked_for_posts

        return context

    def post(self, request, *args, **kwargs):
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('MyApp:post')
        else:
            context = self.get_context_data(**kwargs)
            context['form'] = form
            return self.render_to_response(context)

from django.views import View

class PostJsonView(View):
    def get(self, request, *args, **kwargs):
        posts = Post.objects.all()
        data = list(posts.values())
        return JsonResponse(data, safe=False)
    

@require_POST
@login_required
def post_like(request):
    post_pk = request.POST.get('post_pk')
    context = {
        'user': f'{ request.user }',
    }
    post = get_object_or_404(Post, pk=post_pk)
    like = PostLike.objects.filter(post=post, user=request.user)

    if like.exists():
        like.delete()
        context['method'] = 'delete'
    else:
        like.create(post=post, user=request.user)
        context['method'] = 'create'

    context['postlike_count'] = post.postlike_set.count()

    return JsonResponse(context)

#-----Talk-------

class TalkView(ListView):
    model = Talk
    template_name = 'talk.html'
    context_object_name = 'talks'
    
    def get_queryset(self):
        queryset = super().get_queryset()
        if 'popularity' in self.request.GET:
            queryset = queryset.annotate(num_likes=Count('talklike')).order_by('-num_likes')
        else:
            queryset = queryset.order_by('-date_posted')
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        talklike_counts = []
        is_user_liked_for_talks = []
        for talk in context['talks']:
            talklike_count = talk.talklike_set.count()
            talklike_counts.append(talklike_count)

            if talk.talklike_set.filter(user=self.request.user).exists():
                is_user_liked_for_talk = True
            else:
                is_user_liked_for_talk = False
            is_user_liked_for_talks.append(is_user_liked_for_talk)

        context['talklike_counts'] = talklike_counts
        context['is_user_liked_for_talks'] = is_user_liked_for_talks

        return context


class TalkDetailView(DetailView):
    model = Talk
    template_name = 'talkDetail.html'
    context_object_name = 'talk'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        talk = self.get_object()  # ポストを取得
        talk.views += 1  # viewsを1増やす
        talk.save()  # データベースに保存

        talklike_count = self.object.talklike_set.count()
        # ポストに対するイイね数
        context['talklike_count'] = talklike_count
        # ログイン中のユーザーがイイねしているかどうか
        if self.object.talklike_set.filter(user=self.request.user).exists():
            context['is_user_liked_for_talk'] = True
        else:
            context['is_user_liked_for_talk'] = False

        return context

class TalkCreateView(LoginRequiredMixin, TemplateView):
    template_name = 'talk_create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['talks'] = Talk.objects.filter(author=self.request.user)
        context['form'] = TalkForm()

        talklike_counts = []
        is_user_liked_for_talks = []
        for talk in context['talks']:
            talklike_count = talk.talklike_set.count()
            talklike_counts.append(talklike_count)

            if talk.talklike_set.filter(user=self.request.user).exists():
                is_user_liked_for_talk = True
            else:
                is_user_liked_for_talk = False
            is_user_liked_for_talks.append(is_user_liked_for_talk)

        context['talklike_counts'] = talklike_counts
        context['is_user_liked_for_talks'] = is_user_liked_for_talks

        return context

    def post(self, request, *args, **kwargs):
        form = TalkForm(request.POST)
        if form.is_valid():
            talk = form.save(commit=False)
            talk.author = request.user
            talk.save()
            return redirect('MyApp:talk')
        else:
            context = self.get_context_data(**kwargs)
            context['form'] = form
            return self.render_to_response(context)


@require_POST
@login_required
def talk_like(request):
    talk_pk = request.POST.get('talk_pk')
    context = {
        'user': f'{ request.user }',
    }
    talk = get_object_or_404(Talk, pk=talk_pk)
    like = TalkLike.objects.filter(talk=talk, user=request.user)

    if like.exists():
        like.delete()
        context['method'] = 'delete'
    else:
        like.create(talk=talk, user=request.user)
        context['method'] = 'create'

    context['talklike_count'] = talk.talklike_set.count()

    return JsonResponse(context)

#----------------MyPage----------------------

class MyPageView(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = 'myPage.html'
    context_object_name = 'profiles'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = self.get_object()
        context['posts'] = Post.objects.filter(author=profile.user)
        return context

class MyPageCreateView(LoginRequiredMixin, CreateView):
    model = Profile
    fields = ['name','icon','bio','age','gender','university','sns_account','hobby','language']
    template_name = 'myPage_create.html'
    
    def get_success_url(self):
        return reverse_lazy('MyApp:myPage', kwargs={'pk': self.object.pk})
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    
class MyPageUpdateView(LoginRequiredMixin, UpdateView):

MySNS/MyApp/templates/base.html
<!doctype html>
{% load static %} 
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Kameron:wght@400;700&family=Noto+Sans+JP:wght@500&display=swap" rel="stylesheet"/>
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
    {% comment %} <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.1/mdb.min.css" rel="stylesheet" /> {% endcomment %}
    <link rel="stylesheet" href="{% static 'styles/vendors/css-reset.css' %}" />
    <link rel="stylesheet" href="{% static 'styles/vendors/swiper-bundle.min.css' %}" />
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">

    {% block javaScript %}
    {% endblock javaScript %}

    {% block customcss %}
    {% endblock customcss %}
    <title>MyCode</title>
  </head>
  <body>
    <div id="global-container">
      <div id="container">
        <div class="mobile-menu__cover"></div>
            <header class="header">
              <div class="header__inner">
                <div class="logo">
                  <img src="" class="img__logo" alt="">
                  <a class="header__a" href="{% url 'MyApp:index' %}">
                    <span class="logo__My header__My">My</span>
                    <span class="logo__Code">Code</span>
                  </a>
                </div>
                <nav class="header__nav">
                  <ul class="header__ul">
                    {% if user.is_authenticated %}
                      <li class="header__li"><a href="{% url 'MyApp:logout' %}">{{user}}-Logout</a></li>
                    {% else %}
                      <li class='header__li'>
                          <a href="{% url 'MyApp:login' %}">Login</a>
                      </li>
                      <li class="header__li">
                          <a href="{% url 'MyApp:login' %}"> Sign up </a>
                      </li>
                    {% endif %}
                    <li class="header__li"><a href="{% url 'MyApp:talk' %}">みんなのつぶやき</a></li>
                    <li class="header__li"><a href="{% url 'MyApp:post' %}">投稿一覧</a></li>
                    {% if user.is_authenticated %}
                      <li class="header__li"><a class="btn filled a-justify" href="{% url 'MyApp:myPage' pk=user.profile.pk %}">MyPage</a></li>
                    {% else %}

                    {% endif %}
                  </ul>
                </nav>
                <button class="mobile-menu__btn">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
              </div>
            </header>
        <div id="content">
          {% block hero %}
          {% endblock %}

          <div id="main-content">
            <main>
              {% block main-content %}
              {% endblock %}
            </main>
          </div>
        </div>

        <div class="footer">
          <div class="logo">
            <img src="" class="img__logo" alt="">
            <span class="logo__My">My</span>
            <span class="logo__Code">Code</span>
          </div>
          <nav class="footer__nav">
            <ul class="footer__ul">
              <li class="footer__li"><a href="{% url 'MyApp:talk' %}">みんなのつぶやき</a></li>
              <li class="footer__li"><a href="{% url 'MyApp:post' %}">投稿一覧</a></li>
            </ul>
          </nav>
        </div>
      </div>
      <nav class="mobile-menu">
        <div class="logo">
          <img src="" class="img__logo" alt="">
          <span class="logo__My">My</span>
          <span class="logo__Code">Code</span>
        </div>
        <ul class="mobile-menu__main">
          <li class="mobile-menu__item">
              <a class="mobile-menu__link" href="{% url 'MyApp:talk' %}">
                  <span class="sub-title">みんなのつぶやき</span>
              </a>
          </li>
          <li class="mobile-menu__item">
              <a class="mobile-menu__link" href="{% url 'MyApp:post' %}">
                  <span class="sub-title">投稿一覧</span>
              </a>
          </li>
          {% if user.is_authenticated %}
          <li class="mobile-menu__item">
            <a class="mobile-menu__link" href="{% url 'MyApp:myPage' pk=user.pk %}">
                <span class="sub-title">MyPage</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'scripts/libs/mobile-menu.js' %}"></script>
    <script src="{% static 'scripts/vendors/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'scripts/libs/hero-slider.js' %}"></script>
    <script src="{% static 'scripts/main.js' %}"></script>
  </body>
</html>

MySNS/MyApp/templates/base2.html
{% extends 'base.html' %}
{% load static %}
{% block main-content %}
<section class="picktext">
    <div class="picktext__all">
        <div class="picktext__header">
            <form>
                <input class="picktext__search" type="text" id="search" name="search" placeholder="検索" onkeypress="return searchOnEnter(event)">
            </form>
            <ul class="picktext__ul">
                <!-- この部分に人気順、最近のURL記述 -->
                {% block popularity-sort %}
                {% endblock popularity-sort %}
            </ul>
        </div>
        <div class="picktext__inner">
            <div class="picktext__container">
                {% block main-talk-post %}
                {% endblock main-talk-post %}
            </div>
        </div>

    </div>
    <div class="picktext__create">
        <button class="picktext__btn">
            {% block main-create %}
            {% endblock main-create %}
        </button>

        <button class="picktext__add">
            {% block main-create2 %}
            {% endblock main-create2 %}
        </button>

    </div>
</section>
{% endblock main-content %}

MySNS/MyApp/templates/login_signup.html
<div class="">
    <h2>LOGIN</h2>
    <form method="post">
      {% csrf_token %} 
      {{ login_form.as_p }}
      <button type="submit" name="login_form_submit">LOGIN</button>
    </form>
  
    <h2>SIGN UP</h2>
    <form method="post">
      {% csrf_token %} 
      {{ signup_form.as_p }}
      <button type="submit" name="signup_form_submit">SIGN UP</button>
    </form>
  </div>
  

MySNS/MyApp/templates/myPage_create.html
<form method="post">
    {% csrf_token %}
    <input type="hidden" name="pk" value="{{ object.pk }}">
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">create</button>
    </form>
    

MySNS/MyApp/templates/post_create.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}

{% block javaScript %}
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
{% endblock javaScript %}

{% block customcss %}
<link rel="stylesheet" href="{% static 'styles/create/post_create.css' %}">
{% endblock customcss %}

{% block main-content %}
<section class="post-create">
  <div class="post-create__inner">
    <div class="post-create__container">
      <div class="post-create__header">
        <h2 class="main-title">新しい投稿</h2>
      </div>

      <div class="post-create__new">
        <div class="post-create__newtitle">
          <h2>投稿内容</h2>
        </div>
        <div class="post-create__newpost">
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="post-create__newpost-title">
              <p>タイトル</p>
              <input class="post-create__newpost-name" type="text" name="title" maxlength="50" required="" id="id_title">
            </div>
            <p>内容</p>
            <textarea class="post-create__newpost-textarea" name="content" cols="40" rows="10" maxlength="1000" required="" id="id_content"></textarea> 
            <p>画像</p>
            <input class="post-create__newpost-img" type="file" name="image" accept="image/*" id="id_image">
            <p>カテゴリー</p>
            <select class="post-create__newpost-select" name="category" id="id_category">
              <option value="なし" selected="">なし</option>
              <option value="AI">AI</option>
              <option value="Python">Python</option>
              <option value="java">java</option>
            </select>
            <br>
            <div class="post-create__newpost-btnjustify">
              <button type="submit" class="btn btn-primary post-create__newpost-btn">投稿</button>
            </div>
          </form>
        </div>
      </div>

      <div class="post-create__past">
        <div class="post-create__pasttitle">
          <h2>過去の投稿</h2>
        </div>
        <div class="post-create__pastpost">
          {% for post, is_user_liked_for_post in posts|zip_lists:is_user_liked_for_post %}
                <div class="mypost__usercontainer">
                    <div class="mypost__userimgcontainer">
                        <img src="{{ post.image.url }}" alt="" class="mypost__img">
                    </div>
                    <div class="mypost__userbody-operation">
                        <div class="mypost__userbody">
                            <p class="mypost__usertitle">{{ post.title }}</p>
                            <p>{{ post.category }}</p>
                            <p class="mypost__usercontent">{{ post.content }}</p>
                        </div>
                        <div class="mypost__operation">
                            <div class="mypost__good">
                              {% if is_user_liked_for_post %}
                              <button type="button" id="ajax-like-for-post-{{ post.pk }}" style="border:none;background:none">
                              <!-- すでにイイねしている時はfasクラス -->
                              <i class="fas fa-heart text-danger" id="like-for-post-icon-{{ post.pk }}"></i>
                              </button>
                              {% else %}
                              <button type="button" id="ajax-like-for-post-{{ post.pk }}" style="border:none;background:none">
                              <!-- イイねしていないときはfarクラス -->
                              <i class="far fa-heart text-danger" id="like-for-post-icon-{{ post.pk }}"></i>
                              </button>
                              {% endif %}
                              <!-- イイねの数 -->
                              <span id="postlike_count-{{ post.pk }}">{{ post.postlike_set.count }}</span>
                              <span>いいね</span>
                            </div>
            
                            <div class="mypost__watch">
                                <i class="fas fa-eye"></i>
                                <span>{{post.views}}</span>
                                <span>閲覧</span>
                            </div>
                            <button class="mypost__btn"><a href="{% url 'MyApp:post_detail' pk=post.pk %}" class="mypost__a">詳細を見る</a></button>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
      </div>
    </div>
  </div>
</section>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    /* ポストに対するイイね */
    document.querySelectorAll('[id^="ajax-like-for-post"]').forEach(button => {
    button.addEventListener('click', e => {
        e.preventDefault();
        const postPk = button.id.split('-')[4];
        console.log(postPk)
        const url = '{% url "MyApp:post_like" %}';
        fetch(url, {
            method: 'POST',
            body: `post_pk=${postPk}`,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8',
                'X-CSRFToken': '{{ csrf_token }}',
            },
        }).then(response => {
            return response.json();
        }).then(response => {
            // イイね数を書き換える
            const counter = document.getElementById(`postlike_count-${postPk}`)
            console.log(counter)
            counter.textContent = response.postlike_count
            const icon = document.getElementById(`like-for-post-icon-${postPk}`)
            // 作成した場合はハートを塗る
            if (response.method == 'create') {
                icon.classList.remove('far')
                icon.classList.add('fas')
            } else {
                icon.classList.remove('fas')
                icon.classList.add('far')
            }
        }).catch(error => {
            console.log(error);
        });
    });
});

</script>

{% endblock main-content %}

MySNS/MyApp/templates/signup.html
{% extends 'base.html' %}

{% block main-content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}